[workspace]
resolver = "3"
members = ["crates/a3-domain"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.93.1"
license = "GPL-3.0-only"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
