//! Generates Tauri context, command permissions, and platform resources.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "list_recent_projects",
            "cancel_deep_map",
            "compile_task_lens",
            "control_agent_task_run",
            "create_agent_goal",
            "open_project",
            "pause_deep_map",
            "query_deep_map",
            "query_index_activity",
            "query_index_overview",
            "query_agent_activity",
            "query_agent_goal",
            "query_agent_task_recovery",
            "query_module_card_freshness",
            "query_module_card_detail",
            "query_module_card_evidence",
            "query_module_dependency_graph",
            "query_module_runtime_flow",
            "query_module_runtime_map",
            "query_module_tree",
            "query_project_map_search",
            "query_repository_tree",
            "query_task_lens_task",
            "query_task_lens_tasks",
            "query_project_status",
            "query_health",
            "rebuild_project_index",
            "resume_deep_map",
            "remove_project",
            "revise_agent_goal",
            "start_deep_map",
        ]),
    ))?;
    Ok(())
}
