//! Framework-independent domain model and invariants for A^3.

mod health;
mod job;
mod platform;
mod progress;
mod project;
mod version;

pub use health::Health;
pub use job::{JobId, JobOwner, JobStatus};
pub use platform::Platform;
pub use progress::{Progress, ProgressTransitionError, ProgressValueError};
pub use project::{
    AcceptanceCriterion, AcceptanceCriterionId, AcceptanceCriterionRequirement,
    AcceptanceCriterionStatement, AcceptanceCriterionVerification, AcceptanceVerificationError,
    AcceptanceVerificationReceipt, ActionClass, AgentAction, AgentActionLimit,
    AgentActionLimitError, AgentActionSchemaVersion, AgentActionSchemaVersionError,
    AgentActionTextError, AgentActionTextViolation, AgentBudgetDimension,
    AgentBudgetEvaluationError, AgentBudgetExhaustion, AgentControllerState,
    AgentDiagramArtifactId, AgentFileInspection, AgentFileLineCount, AgentFileLineCountError,
    AgentFileStartLine, AgentFileStartLineError, AgentFinishAction, AgentGraphInspection,
    AgentInspectAction, AgentInspectTarget, AgentLedgerUpdate, AgentMutationAttempt,
    AgentMutationAttemptError, AgentMutationDisposition, AgentMutationKind, AgentQueuedMessage,
    AgentQueuedMessageId, AgentQueuedMessageState, AgentQueuedResearchSelection, AgentRepairLimit,
    AgentRepairLimitError, AgentResearchDepth, AgentRun, AgentRunAction, AgentRunBudget,
    AgentRunDurationLimit, AgentRunDurationLimitError, AgentRunError, AgentRunId, AgentRunIdentity,
    AgentRunMaterializedState, AgentRunTimestamp, AgentRunTimestampError, AgentRunTiming,
    AgentRunUsage, AgentRunUsageError, AgentSearchAction, AgentSearchLimit, AgentSearchLimitError,
    AgentSearchQuery, AgentSession, AgentSessionEntry, AgentSessionEntryError,
    AgentSessionEntryKind, AgentSessionId, AgentSessionMode, AgentSessionQueueRevision,
    AgentSessionRevision, AgentSessionRevisionError, AgentSessionSequence, AgentSessionState,
    AgentSessionText, AgentSessionTextError, AgentSessionTimestamp, AgentSessionTitle,
    AgentTestSelector, AgentTokenLimit, AgentTokenLimitError, AgentToolAttempt,
    AgentToolAttemptError, AgentToolAttemptNumber, AgentToolAttemptNumberError,
    AgentToolAttemptStatus, AgentToolEvidence, AgentToolEvidenceLocation, AgentToolEvidenceSet,
    AgentToolEvidenceSetError, AgentTurnActionClass, AgentTurnCharge, AgentTurnLimit,
    AgentTurnLimitError, AgentTurnRepairUsage, AgentUpdateLedgerAction, AgentWorkItem,
    AgentWorkItemId, AgentWorkPlan, AgentWorkPlanError, AgentWorkPlanStep,
    AgentWorkPlanVerificationIntent, ApprovalGrant, ApprovalGrantError, ApprovalGrantState,
    ApprovalId, ApprovalRequest, ApprovalRequestError, ApprovalRequestId, ApprovalRevokeError,
    ApprovalStatus, ApprovalUseError, AskResearchCompleteness, AskResearchPhase,
    AskResearchSelectionReason, AskResearchSourceId, AskResearchSourceKind, AskResearchState,
    BodyHash, CandidateFreshness, CandidateSetCompleteness, CandidateTokenCost,
    CandidateTokenCostError, CanonicalDirectory, CanonicalDirectoryError, Centrality,
    CentralityError, CommandCatalogError, CommandCatalogId, CommandDiscoveryEvidence,
    CommandDiscoverySchemaVersion, CommandEvidence, CommandEvidenceContext, CompactedRunClaim,
    CompactedStepResult, Confidence, ConfidenceError, ContentHash, ContextBudgetError,
    ContextBudgetPlan, ContextBudgetUsage, ContextCompilerPolicyVersion, ContextDigest,
    ContextSection, CoverageRequirement, DeepMapDiagnosticCode, DeepMapEventSequence,
    DeepMapEventSequenceError, DeepMapMode, DeepMapPlanError, DeepMapPlanner, DeepMapRunId,
    DeepMapRunState, DeepMapRunTimestamp, DeepMapRunTimestampError, DiagnosticCount,
    DiagnosticEvidence, DiagnosticMessage, DiagnosticMessageError, DiagnosticPolicy, DiffEvidence,
    DiffEvidenceSource, DiffInvariantMode, DiffInvariantVerification,
    DiffInvariantVerificationError, DirectoryPageSize, DirectoryPageSizeError, DiscoveredCommand,
    DiscoveredCommandError, DiscoveredCommandId, DiscoveredCommandKind,
    DiscoveredCommandProcessError, DiscoveredFile, DiscoveredFileRole, DiscoveredFileRoles,
    DiscoveredFileRolesError, DiscoveryExclusionCounts, DiscoveryExclusionReason, DiscoveryOrigin,
    DiscoveryPolicy, DiscoveryPolicyVersion, DiscoveryPolicyVersionError, DiscoveryResult,
    DiscoveryResultError, EmbeddingBatchSize, EmbeddingBatchSizeError, EmbeddingCacheKey,
    EmbeddingDataType, EmbeddingDimension, EmbeddingDimensionError, EmbeddingModelId,
    EmbeddingModelProfile, EmbeddingProfileTextError, EmbeddingProfileTextKind,
    EmbeddingProviderId, EmbeddingQuantization, EmbeddingTimestamp, EmbeddingTimestampError,
    EmbeddingVector, EmbeddingVectorError, EmbeddingVectorNormalization, EvidenceDependency,
    EvidenceFreshness, EvidenceFreshnessFailure, EvidenceRef, ExactSearchCursor,
    ExactSearchCursorError, ExactSearchExplanation, ExactSearchHit, ExactSearchHitError,
    ExactSearchPage, ExactSearchPageError, ExactSearchPageSize, ExactSearchPageSizeError,
    ExactSearchPosition, ExactSearchQuery, ExactSearchRole, ExactSearchSymbol, ExactSearchTarget,
    ExactSearchTerm, ExactSearchTextError, ExpectedInformationGain, ExpectedInformationGainError,
    ExpectedTaskEvidence, ExplorationStopPolicy, ExplorationStopReason, ExplorationStopState,
    ExploreBudget, ExploreBudgetError, ExploreCost, ExploreCostError, ExploreEvidenceRequirement,
    ExplorePlan, ExplorePlanStopReason, ExplorePolicyVersion, ExploreSeedReason, ExploreStep,
    ExploreStepStatus, ExploreTarget, ExploreVerificationMethod, ExplorerAction,
    ExplorerActionSchemaVersion, ExplorerCheckpoint, ExplorerCheckpointError,
    ExplorerInspectAction, ExplorerSearchAction, ExplorerSearchActionError, ExplorerSearchKind,
    ExplorerSearchLimit, ExplorerSearchQuery, FileDelta, FileRevision, FusedRetrievalHit,
    FusedRetrievalResult, FusionContribution, FusionError, FusionPolicy, FusionPolicyVersion,
    FusionPriority, FusionResultLimit, FusionResultLimitError, FusionScore,
    FusionSignalExplanation, FusionTokenExplanation, GitHead, GitObjectId, GitObjectIdError,
    GitPolicyOperation, GitReferenceName, GitReferenceNameError, GoalConstraint, GoalContract,
    GoalContractCollection, GoalContractDraft, GoalContractDraftError, GoalContractHistory,
    GoalContractHistoryError, GoalContractReference, GoalContractRestoreError,
    GoalContractRevision, GoalContractRevisionError, GoalContractRevisionFailure,
    GoalContractTextError, GoalContractTextField, GoalContractTextViolation, GoalContractTimestamp,
    GoalContractTimestampError, GoalObjective, GoalRevisionReason, GraphEdge, GraphEndpoint,
    GraphSymbol, GraphTraversalHit, GraphTraversalHitError, GraphTraversalResult,
    GraphTraversalResultError, GraphTraversalTarget, IndexInvalidationPlan, IndexLanguage,
    IndexPublication, IndexPublicationError, IndexRunId, IndexRunRecord, IndexRunSequence,
    IndexRunSequenceError, IndexRunStart, IndexRunStatus, IndexRunStatusError,
    IndexRunTerminalOutcome, IndexSchemaVersion, IndexSchemaVersionError, IndexedFileAnalysis,
    IndexedFileAnalysisError, InformationGainRationale, InformationGainRationaleError,
    InvalidationPlanError, InvalidationReason, LanguageAdapterContractVersion,
    LanguageAdapterContractVersionError, LanguageAdapterRevision, LanguageAdapterVersion,
    LanguageAdapterVersionError, LanguageParseArtifacts, LanguageParseResult,
    LanguageParseResultError, LexicalScore, LexicalScoreError, LexicalSearchCursor,
    LexicalSearchExplanation, LexicalSearchHit, LexicalSearchPage, LexicalSearchPageError,
    LexicalSearchPageSize, LexicalSearchPageSizeError, LexicalSearchPosition, LexicalSearchQuery,
    LexicalSearchSymbol, LexicalSearchTarget, LexicalSearchTerm, LexicalSearchTermError,
    LinkResolution, LinkedGraph, LinkedGraphError, LocalSymbolId, LocalSymbolIdError,
    MAX_AGENT_WORK_PLAN_STEPS, MapperProfileVersion, MapperProfileVersionError,
    MemoryCandidateExplanation, MemoryCandidateExplanationError, MinimumTestCaseCount,
    MinimumTestCaseCountError, ModelCapabilities, ModelContextLimit, ModelContextLimitError,
    ModelId, ModelIdentityError, ModelIdentityKind, ModelOutputLimit, ModelOutputLimitError,
    ModelParallelismLimit, ModelParallelismLimitError, ModelProfile, ModelProfileError,
    ModelProfileId, ModelProfileOverride, ModelProfileOverrideError, ModelProfileOverrideRevision,
    ModelProfileOverrideRevisionError, ModelProfileReference, ModelProfileSettings,
    ModelProfileSource, ModelProfileVersion, ModelProfileVersionError, ModelPromptSchemaGrounding,
    ModelProviderId, ModelSamplingProfile, ModelStopSequence, ModelStopSequenceError,
    ModelStopSequences, ModelStopSequencesError, ModelStructuredOutputCapability, ModelTemperature,
    ModelTemperatureError, ModelTokenCount, ModelTokenCountError, ModelTokenCountingStrategy,
    ModelToolCallMode, ModelTopP, ModelTopPError, ModuleCardClaimId, ModuleCardContradiction,
    ModuleCardContradictionReport, ModuleCardEvidenceId, ModuleCardField, ModuleCardFieldSpec,
    ModuleCardId, ModuleCardInvalidation, ModuleCardInvalidationCandidate, ModuleCardMetadataField,
    ModuleCardProposal, ModuleCardProposalEnvelope, ModuleCardProposalError, ModuleCardSchema,
    ModuleCardSchemaVersion, ModuleCardStatus, ModuleCardVerificationCandidate,
    ModuleCardVerificationError, ModuleCardVerifier, ModuleClaimEnvelope, ModuleClaimPolarity,
    ModuleClaimPredicate, ModuleClaimProposal, ModuleClaimProposalError, ModuleClaimSchemaVersion,
    ModuleClaimStatement, ModuleClaimStatementError, ModuleCoverage, ModuleCoverageSnapshot,
    ModuleId, ModuleKind, ModuleMapError, ModuleMembership, ModuleMembershipEvidence,
    ModuleMembershipKind, ModulePolicyVersion, ModulePolicyVersionError, ModuleProjection,
    ModuleRoot, ModuleSymbolSet, MutationActionFingerprint, MutationActionFingerprintError,
    MutationApplicationState, MutationReconciliation, NetworkPurpose, NonGoal,
    NormalizedRetrievalSignal, NormalizedRetrievalSignalError, NormalizedSemanticCard,
    OpenRunIssue, OpenRunIssueKind, ParseCoverage, ParseCoverageError, ParseDiagnostic,
    ParseDiagnosticCode, ParseDiagnosticSeverity, ParsedSlashCommand, ParsedSymbol,
    ParsedSymbolError, PatchAction, PatchActionDigest, PatchActionError, PatchActionSchemaVersion,
    PatchAdd, PatchChange, PatchChangeSet, PatchChangeSetError, PatchContentPreview,
    PatchFileContent, PatchFileContentError, PatchLineEndings, PatchMove, PatchOperation,
    PatchOperationError, PatchPolicyAction, PatchPreview, PatchPreviewEntry, PatchPreviewError,
    PatchRationale, PatchRationaleError, PatchScopeDigest, PatchTextEncoding, PatchUpdate,
    PathPolicyOperation, PathScopeCoverage, PolicyAction, PolicyActionFingerprint, PolicyDecision,
    PolicyDecisionError, PolicyDecisionId, PolicyDecisionOutcome, PolicyDecisionReason,
    PolicyDisposition, PolicyEvaluationTiming, PolicyEvaluationTimingError, PolicyPathScope,
    PolicyResourceId, PolicyScopeDigest, ProcessArgument, ProcessArgumentError, ProcessDuration,
    ProcessEnvironmentVariable, ProcessEnvironmentVariableError, ProcessEvent, ProcessEventKind,
    ProcessEventSequence, ProcessEventSequenceError, ProcessExecutable, ProcessExecutableError,
    ProcessExecutionMode, ProcessExit, ProcessExitError, ProcessNetworkScope, ProcessOutputCapture,
    ProcessOutputCaptureError, ProcessOutputChunk, ProcessOutputChunkError, ProcessOutputContent,
    ProcessOutputContentError, ProcessOutputDigest, ProcessOutputLimit, ProcessOutputLimitError,
    ProcessOutputRedaction, ProcessPlanBinding, ProcessPolicyAction, ProcessRunResult,
    ProcessRunResultError, ProcessSpec, ProcessSpecError, ProcessSpecSchemaVersion, ProcessStream,
    ProcessStreamEvidence, ProcessTermination, ProcessTimeout, ProcessTimeoutError,
    ProjectCommandAllowlist, ProjectCommandAllowlistError, ProjectCommandCatalog, ProjectId,
    ProjectIdentity, ProjectIdentityError, ProposedModuleCardField, PublishedIndex,
    QualifiedSymbolName, RankProjection, RankProjectionError, RankScore, RankScoreError,
    RankingPolicyVersion, RankingPolicyVersionError, RelationshipCandidateExplanation,
    RemapPriority, RemapRequest, RemapRequestError, RemoteIdentity, RenameCandidate,
    RepositoryCard, RepositoryFileState, RepositoryFileStateError, RepositoryId,
    RepositoryIdentity, RepositoryModule, RepositoryPath, RepositoryPathError,
    ResolvedModuleCardEvidence, ResolvedModuleCardEvidenceSet, ResultExplanation,
    ResultSourceExplanation, RetrievalCandidate, RetrievalCandidateReason, RetrievalCandidateSet,
    RetrievalCandidateSetError, RetrievalCandidateSets, RetrievalCandidateSetsError,
    RetrievalCandidateSignals, RetrievalTargetId, RiskLevel, RootPolicyOperation, RunEvent,
    RunEventCode, RunEventId, RunEventIdentity, RunEventKind, RunEventOccurrence, RunEventOutcome,
    RunEventPayload, RunEventRedaction, RunEventRedactionSource, RunEventSequence,
    RunEventSequenceError, RunEventSubject, RunMemoryCheckpoint, RunMemoryCompileError,
    RunMemoryDigest, RunMemoryPolicyVersion, RunPayloadDigest, SecretCandidateClassifierV1,
    SecretCandidateKind, SemanticCardBatch, SemanticCardBatchError, SemanticCardId,
    SemanticCardNormalizationError, SemanticCardNormalizationVersion, SemanticEmbedding,
    SlashCommand, SlashCommandCatalogVersion, SlashCommandEmptyInput, SlashCommandInvocation,
    SlashCommandLens, SlashCommandParseError, SlashCommandResearchProfile,
    SlashCommandResultContract, SlashCommandVerificationProfile, Snapshot, SnapshotChange,
    SnapshotChangeKind, SnapshotDelta, SnapshotError, SnapshotId, SourceChannel, SourcePosition,
    SourceRange, SourceRangeError, StepDependency, StepResultSource, StepVerification,
    StepVerificationError, StepVerificationId, StepVerificationOutcome, StoredDiffEvidenceContext,
    StoredProcessEvidence, SuccessVerification, SymbolId, SymbolKind, SymbolName, SymbolRank,
    SymbolRankSignals, SymbolReference, SymbolReferenceError, SymbolRole, SymbolRoles,
    SymbolSignature, SymbolTextError, SymbolVisibility, SyntaxProvider, SyntaxRelation,
    SyntaxRelationKind, SyntaxSource, SyntaxTarget, SystemPolicyV1, TaskEvidenceId, TaskId,
    TaskLedger, TaskLedgerError, TaskLedgerInvalidation, TaskLedgerReplan, TaskLedgerRevision,
    TaskLedgerRevisionError, TaskLedgerTimestamp, TaskLedgerTimestampError, TaskLens,
    TaskLensClaim, TaskLensClaimError, TaskLensCompileError, TaskLensDiagnosticKind,
    TaskLensDigest, TaskLensEntry, TaskLensEntryReason, TaskLensPolicy, TaskLensPolicyVersion,
    TaskLensSeed, TaskLensSeedSet, TaskLensSeedSetError, TaskLensSeedText, TaskLensSeedTextError,
    TaskLensTarget, TaskLensTokenBudget, TaskLensTokenBudgetError, TaskLensZoomLevel,
    TaskReplanReason, TaskReplanReasonError, TaskReplanReasonViolation, TaskStep, TaskStepAttempt,
    TaskStepAttemptDetails, TaskStepAttemptNumber, TaskStepAttemptNumberError,
    TaskStepAttemptOutcome, TaskStepAttemptTiming, TaskStepBlockingReason,
    TaskStepCancellationReason, TaskStepDefinition, TaskStepDefinitionError, TaskStepFailureReason,
    TaskStepId, TaskStepMaterializedState, TaskStepOutcome, TaskStepRationale,
    TaskStepResultSummary, TaskStepStaleCause, TaskStepStatus, TaskStepTextError,
    TaskStepTextViolation, TaskStepTransitionError, TaskVerificationTextError,
    TaskVerificationTextViolation, TestCaseEvidence, TestCaseName, TestCaseNameError,
    TestCaseOutcome, TestCaseSelector, TestCaseSelectorName, TestEvidence, ToolRunId,
    ToolRunIdDerivationError, TraversalDepth, TraversalDepthError, TraversalDirection,
    TraversalQuery, TraversalResultLimit, TraversalResultLimitError, UnresolvedEdgeCandidate,
    UnresolvedGraphTarget, UnresolvedReason, UserConfirmationEvidence, UserDecision, VectorHit,
    VectorSearchCapability, VectorSearchLimit, VectorSearchLimitError, VectorSearchResult,
    VectorSearchResultError, VerificationDependencies, VerificationDependenciesError,
    VerificationEvidence, VerificationEvidenceBuildError, VerificationEvidenceEvaluation,
    VerificationEvidenceFailure, VerificationEvidenceSchemaVersion, VerificationFailureSummary,
    VerificationMethod, VerificationRequirement, VerificationRunId, VerificationScope,
    VerificationSpec, VerificationSpecId, VerificationTarget, VerifiedClaimKind,
    VerifiedClaimStatus, VerifiedModuleCard, VerifiedModuleCardBatch, VerifiedModuleClaim,
    WorkspaceDirectory, WorkspaceDirectoryEntry, WorkspaceDirectoryEntryError,
    WorkspaceDirectoryEntryKind, WorkspaceDirectoryListRequest, WorkspaceDirectoryListRequestError,
    WorkspaceDirectoryListing, WorkspaceDirectoryListingError, WorkspacePolicy,
    WorkspacePolicyError, WorkspacePolicyRestriction, WorkspacePolicyRule, WorktreeAnchorId,
    WorktreeGeneration, WorktreeGenerationError, WorktreeId, WorktreeIdentity, parse_slash_command,
};
pub use version::{ApplicationVersion, ApplicationVersionError};
