//! Framework-independent domain model and invariants for A^3.

mod health;
mod job;
mod platform;
mod progress;
mod project;
mod version;

pub use health::Health;
pub use job::{JobId, JobOwner, JobStatus};
pub use platform::Platform;
pub use progress::{Progress, ProgressTransitionError, ProgressValueError};
pub use project::{
    AcceptanceCriterion, AcceptanceCriterionId, AcceptanceCriterionStatement, AgentAction,
    AgentActionLimit, AgentActionLimitError, AgentActionSchemaVersion,
    AgentActionSchemaVersionError, AgentActionTextError, AgentActionTextViolation,
    AgentBudgetDimension, AgentBudgetEvaluationError, AgentBudgetExhaustion, AgentControllerState,
    AgentFileInspection, AgentFileLineCount, AgentFileLineCountError, AgentFileStartLine,
    AgentFileStartLineError, AgentFinishAction, AgentGraphInspection, AgentInspectAction,
    AgentInspectTarget, AgentLedgerUpdate, AgentRepairLimit, AgentRepairLimitError, AgentRun,
    AgentRunBudget, AgentRunDurationLimit, AgentRunDurationLimitError, AgentRunError, AgentRunId,
    AgentRunIdentity, AgentRunMaterializedState, AgentRunTimestamp, AgentRunTimestampError,
    AgentRunTiming, AgentRunUsage, AgentRunUsageError, AgentSearchAction, AgentSearchLimit,
    AgentSearchLimitError, AgentSearchQuery, AgentTestSelector, AgentTokenLimit,
    AgentTokenLimitError, AgentTurnActionClass, AgentTurnCharge, AgentTurnLimit,
    AgentTurnLimitError, AgentTurnRepairUsage, AgentUpdateLedgerAction, BodyHash,
    CandidateFreshness, CandidateSetCompleteness, CandidateTokenCost, CandidateTokenCostError,
    CanonicalDirectory, CanonicalDirectoryError, Centrality, CentralityError, CompactedRunClaim,
    CompactedStepResult, Confidence, ConfidenceError, ContentHash, ContextBudgetError,
    ContextBudgetPlan, ContextBudgetUsage, ContextCompilerPolicyVersion, ContextDigest,
    ContextSection, CoverageRequirement, DeepMapPlanError, DeepMapPlanner, DiagnosticMessage,
    DiagnosticMessageError, DiscoveredFile, DiscoveredFileRole, DiscoveredFileRoles,
    DiscoveredFileRolesError, DiscoveryExclusionCounts, DiscoveryExclusionReason, DiscoveryOrigin,
    DiscoveryPolicy, DiscoveryPolicyVersion, DiscoveryPolicyVersionError, DiscoveryResult,
    DiscoveryResultError, EmbeddingBatchSize, EmbeddingBatchSizeError, EmbeddingCacheKey,
    EmbeddingDataType, EmbeddingDimension, EmbeddingDimensionError, EmbeddingModelId,
    EmbeddingModelProfile, EmbeddingProfileTextError, EmbeddingProfileTextKind,
    EmbeddingProviderId, EmbeddingQuantization, EmbeddingTimestamp, EmbeddingTimestampError,
    EmbeddingVector, EmbeddingVectorError, EmbeddingVectorNormalization, EvidenceRef,
    ExactSearchCursor, ExactSearchCursorError, ExactSearchExplanation, ExactSearchHit,
    ExactSearchHitError, ExactSearchPage, ExactSearchPageError, ExactSearchPageSize,
    ExactSearchPageSizeError, ExactSearchPosition, ExactSearchQuery, ExactSearchRole,
    ExactSearchSymbol, ExactSearchTarget, ExactSearchTerm, ExactSearchTextError,
    ExpectedInformationGain, ExpectedInformationGainError, ExpectedTaskEvidence,
    ExplorationStopPolicy, ExplorationStopReason, ExplorationStopState, ExploreBudget,
    ExploreBudgetError, ExploreCost, ExploreCostError, ExploreEvidenceRequirement, ExplorePlan,
    ExplorePlanStopReason, ExplorePolicyVersion, ExploreSeedReason, ExploreStep, ExploreStepStatus,
    ExploreTarget, ExploreVerificationMethod, ExplorerAction, ExplorerActionSchemaVersion,
    ExplorerCheckpoint, ExplorerCheckpointError, ExplorerInspectAction, ExplorerSearchAction,
    ExplorerSearchActionError, ExplorerSearchKind, ExplorerSearchLimit, ExplorerSearchQuery,
    FileDelta, FileRevision, FusedRetrievalHit, FusedRetrievalResult, FusionContribution,
    FusionError, FusionPolicy, FusionPolicyVersion, FusionPriority, FusionResultLimit,
    FusionResultLimitError, FusionScore, FusionSignalExplanation, FusionTokenExplanation, GitHead,
    GitObjectId, GitObjectIdError, GitReferenceName, GitReferenceNameError, GoalConstraint,
    GoalContract, GoalContractCollection, GoalContractDraft, GoalContractDraftError,
    GoalContractHistory, GoalContractHistoryError, GoalContractReference, GoalContractRestoreError,
    GoalContractRevision, GoalContractRevisionError, GoalContractRevisionFailure,
    GoalContractTextError, GoalContractTextField, GoalContractTextViolation, GoalContractTimestamp,
    GoalContractTimestampError, GoalObjective, GoalRevisionReason, GraphEdge, GraphEndpoint,
    GraphSymbol, GraphTraversalHit, GraphTraversalHitError, GraphTraversalResult,
    GraphTraversalResultError, GraphTraversalTarget, IndexInvalidationPlan, IndexLanguage,
    IndexPublication, IndexPublicationError, IndexRunId, IndexRunRecord, IndexRunSequence,
    IndexRunSequenceError, IndexRunStart, IndexRunStatus, IndexRunStatusError,
    IndexRunTerminalOutcome, IndexSchemaVersion, IndexSchemaVersionError, InformationGainRationale,
    InformationGainRationaleError, InvalidationPlanError, InvalidationReason,
    LanguageAdapterContractVersion, LanguageAdapterContractVersionError, LanguageAdapterRevision,
    LanguageAdapterVersion, LanguageAdapterVersionError, LanguageParseArtifacts,
    LanguageParseResult, LanguageParseResultError, LexicalScore, LexicalScoreError,
    LexicalSearchCursor, LexicalSearchExplanation, LexicalSearchHit, LexicalSearchPage,
    LexicalSearchPageError, LexicalSearchPageSize, LexicalSearchPageSizeError,
    LexicalSearchPosition, LexicalSearchQuery, LexicalSearchSymbol, LexicalSearchTarget,
    LexicalSearchTerm, LexicalSearchTermError, LinkResolution, LinkedGraph, LinkedGraphError,
    LocalSymbolId, LocalSymbolIdError, MapperProfileVersion, MapperProfileVersionError,
    MemoryCandidateExplanation, MemoryCandidateExplanationError, ModelCapabilities,
    ModelContextLimit, ModelContextLimitError, ModelId, ModelIdentityError, ModelIdentityKind,
    ModelOutputLimit, ModelOutputLimitError, ModelParallelismLimit, ModelParallelismLimitError,
    ModelProfile, ModelProfileError, ModelProfileId, ModelProfileOverride,
    ModelProfileOverrideError, ModelProfileOverrideRevision, ModelProfileOverrideRevisionError,
    ModelProfileReference, ModelProfileSettings, ModelProfileSource, ModelProfileVersion,
    ModelProfileVersionError, ModelPromptSchemaGrounding, ModelProviderId, ModelSamplingProfile,
    ModelStopSequence, ModelStopSequenceError, ModelStopSequences, ModelStopSequencesError,
    ModelStructuredOutputCapability, ModelTemperature, ModelTemperatureError, ModelTokenCount,
    ModelTokenCountError, ModelTokenCountingStrategy, ModelToolCallMode, ModelTopP, ModelTopPError,
    ModuleCardClaimId, ModuleCardContradiction, ModuleCardContradictionReport,
    ModuleCardEvidenceId, ModuleCardField, ModuleCardFieldSpec, ModuleCardId,
    ModuleCardInvalidation, ModuleCardInvalidationCandidate, ModuleCardMetadataField,
    ModuleCardProposal, ModuleCardProposalEnvelope, ModuleCardProposalError, ModuleCardSchema,
    ModuleCardSchemaVersion, ModuleCardStatus, ModuleCardVerificationCandidate,
    ModuleCardVerificationError, ModuleCardVerifier, ModuleClaimEnvelope, ModuleClaimPolarity,
    ModuleClaimPredicate, ModuleClaimProposal, ModuleClaimProposalError, ModuleClaimSchemaVersion,
    ModuleClaimStatement, ModuleClaimStatementError, ModuleCoverage, ModuleCoverageSnapshot,
    ModuleId, ModuleKind, ModuleMapError, ModuleMembership, ModuleMembershipEvidence,
    ModuleMembershipKind, ModulePolicyVersion, ModulePolicyVersionError, ModuleProjection,
    ModuleRoot, ModuleSymbolSet, NonGoal, NormalizedRetrievalSignal,
    NormalizedRetrievalSignalError, NormalizedSemanticCard, OpenRunIssue, OpenRunIssueKind,
    ParseCoverage, ParseCoverageError, ParseDiagnostic, ParseDiagnosticCode,
    ParseDiagnosticSeverity, ParsedSymbol, ParsedSymbolError, ProjectId, ProjectIdentity,
    ProjectIdentityError, ProposedModuleCardField, PublishedIndex, QualifiedSymbolName,
    RankProjection, RankProjectionError, RankScore, RankScoreError, RankingPolicyVersion,
    RankingPolicyVersionError, RelationshipCandidateExplanation, RemapPriority, RemapRequest,
    RemapRequestError, RemoteIdentity, RenameCandidate, RepositoryCard, RepositoryFileState,
    RepositoryFileStateError, RepositoryId, RepositoryIdentity, RepositoryModule, RepositoryPath,
    RepositoryPathError, ResolvedModuleCardEvidence, ResolvedModuleCardEvidenceSet,
    ResultExplanation, ResultSourceExplanation, RetrievalCandidate, RetrievalCandidateReason,
    RetrievalCandidateSet, RetrievalCandidateSetError, RetrievalCandidateSets,
    RetrievalCandidateSetsError, RetrievalCandidateSignals, RetrievalTargetId, RunEvent,
    RunEventCode, RunEventId, RunEventIdentity, RunEventKind, RunEventOccurrence, RunEventOutcome,
    RunEventPayload, RunEventRedaction, RunEventRedactionSource, RunEventSequence,
    RunEventSequenceError, RunEventSubject, RunMemoryCheckpoint, RunMemoryCompileError,
    RunMemoryDigest, RunMemoryPolicyVersion, RunPayloadDigest, SemanticCardBatch,
    SemanticCardBatchError, SemanticCardId, SemanticCardNormalizationError,
    SemanticCardNormalizationVersion, SemanticEmbedding, Snapshot, SnapshotChange,
    SnapshotChangeKind, SnapshotDelta, SnapshotError, SnapshotId, SourceChannel, SourcePosition,
    SourceRange, SourceRangeError, StepDependency, StepResultSource, StepVerification,
    StepVerificationError, StepVerificationId, StepVerificationOutcome, SuccessVerification,
    SymbolId, SymbolKind, SymbolName, SymbolRank, SymbolRankSignals, SymbolReference,
    SymbolReferenceError, SymbolRole, SymbolRoles, SymbolSignature, SymbolTextError,
    SymbolVisibility, SyntaxProvider, SyntaxRelation, SyntaxRelationKind, SyntaxSource,
    SyntaxTarget, TaskEvidenceId, TaskId, TaskLedger, TaskLedgerError, TaskLedgerInvalidation,
    TaskLedgerReplan, TaskLedgerRevision, TaskLedgerRevisionError, TaskLedgerTimestamp,
    TaskLedgerTimestampError, TaskLens, TaskLensClaim, TaskLensClaimError, TaskLensCompileError,
    TaskLensDiagnosticKind, TaskLensDigest, TaskLensEntry, TaskLensEntryReason, TaskLensPolicy,
    TaskLensPolicyVersion, TaskLensSeed, TaskLensSeedSet, TaskLensSeedSetError, TaskLensSeedText,
    TaskLensSeedTextError, TaskLensTarget, TaskLensTokenBudget, TaskLensTokenBudgetError,
    TaskLensZoomLevel, TaskReplanReason, TaskReplanReasonError, TaskReplanReasonViolation,
    TaskStep, TaskStepAttempt, TaskStepAttemptDetails, TaskStepAttemptNumber,
    TaskStepAttemptNumberError, TaskStepAttemptOutcome, TaskStepAttemptTiming,
    TaskStepBlockingReason, TaskStepCancellationReason, TaskStepDefinition,
    TaskStepDefinitionError, TaskStepFailureReason, TaskStepId, TaskStepMaterializedState,
    TaskStepOutcome, TaskStepRationale, TaskStepResultSummary, TaskStepStaleCause, TaskStepStatus,
    TaskStepTextError, TaskStepTextViolation, TaskStepTransitionError, TaskVerificationTextError,
    TaskVerificationTextViolation, ToolRunId, TraversalDepth, TraversalDepthError,
    TraversalDirection, TraversalQuery, TraversalResultLimit, TraversalResultLimitError,
    UnresolvedEdgeCandidate, UnresolvedGraphTarget, UnresolvedReason, UserDecision, VectorHit,
    VectorSearchCapability, VectorSearchLimit, VectorSearchLimitError, VectorSearchResult,
    VectorSearchResultError, VerificationFailureSummary, VerificationMethod,
    VerificationRequirement, VerificationSpec, VerificationSpecId, VerifiedClaimKind,
    VerifiedClaimStatus, VerifiedModuleCard, VerifiedModuleCardBatch, VerifiedModuleClaim,
    WorktreeAnchorId, WorktreeGeneration, WorktreeGenerationError, WorktreeId, WorktreeIdentity,
};
pub use version::{ApplicationVersion, ApplicationVersionError};
